# SciPy2018 tutorial: Introduction to Numerical Computing with NumPy

In [3]:
#Creo2 listas
a = [1,2,3,4]
b = [10,11,12,13]

In [4]:
#Por como python suma las listas el resultado es el siguiente, lo cual es una CONCATENACION
a+b

[1, 2, 3, 4, 10, 11, 12, 13]

In [5]:
#Para sumar item a item lo tengo que realizar por medio de un loop

output = [] #Inicializo un loop vacio
for item1,item2 in zip(a,b):
    output.append(item1+item2)

In [6]:
output

[11, 13, 15, 17]

In [7]:
#Creo una lista de 1 millon de elementos

g = list(range(1000000))
%timeit sum(g)

23.7 ms ± 894 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [8]:
import numpy as np #La forma abreviada de importar numpy

In [9]:
#Agarro la lista g creada con anterioridad y la paso a un array de NumPy

g_array = np.array(g)

In [10]:
%timeit np.sum(g_array) #Sumo por medio de NumPy

479 µs ± 11.8 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Esta mejora en el tiempo de debe a la diferencia en la estructura de datos del array de NumPy comparado con la estructura de datos de las listas de Python. Esto permite que las operaciones sean mas rapidas.

In [11]:
#Creo 2 arrays en forma manual con la sintaxis np.array de NumPy
a = np.array([1,2,3,4])
b = np.array([11,12,13,14])

In [12]:
a

array([1, 2, 3, 4])

In [13]:
b

array([11, 12, 13, 14])

La forma que tiene Python de diferenciar una lista de un ndarray de NumPy es por medio de la palabra array adelante de los mismos

In [14]:
#Realizo la suma de los arrays item a item. Numpy internamente esta realizando los "FOR LOOPS" punto a punto

a+b

array([12, 14, 16, 18])

In [15]:
a*b #Producto punto a punto

array([11, 24, 39, 56])

In [16]:
a/b #Division punto a punto

array([0.09090909, 0.16666667, 0.23076923, 0.28571429])

In [17]:
a**b #Exponente punto a punto

array([        1,      4096,   1594323, 268435456], dtype=int32)

# Tipo de datos, dimensiones y tamaño del array

El tipo de objeto de NumPy es "ndarray", el cual siginifica n-dimensional array (multidimensional array)

Es importante destacar que en un array TODOS los elementos del mismo deben ser del mismo tipo (int,float,etc), lo cual significa que es HOMOGENEO

Dtype significa "data type"

In [18]:
type(a) #Typo de objeto, el cual corresponde a un array de NumPy

numpy.ndarray

In [19]:
a.dtype #Tipo de dato del array

dtype('int32')

In [20]:
a.ndim #Numero de dimensiones. En este caso es unidimensional (1 dimension)

1

In [21]:
a.shape #Tamaño del array. Es uno de los atributos mas importantes de un array ya que define en parte como interacciona con otros arrays

#Devuelve una tupla () con el numero de elementos en cada dimension

#En este ejemplo se tiene una dimension con 4 elementos

(4,)

In [22]:
a

array([1, 2, 3, 4])

In [23]:
b

array([11, 12, 13, 14])

In [24]:
a*10

array([10, 20, 30, 40])

In [25]:
a*100

array([100, 200, 300, 400])

En los casos anteriores de multiplicacion por una constante NumPy realiza lo que se llama BROADCASTING, lo que significa aplicar la transformacion deseada a cada elemento en el array

# UFUNC: Universal Functions

In [26]:
np.sin(a) #Realiza el calculo del seno (a) para cada elemento del array

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [27]:
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [28]:
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

In [29]:
np.log

<ufunc 'log'>

In [30]:
np.sum

<function numpy.core.fromnumeric.sum(a, axis=None, dtype=None, out=None, keepdims=<class 'numpy._globals._NoValue'>)>

# Setting array elements

NumPy asi como Python tiene indexacion 0, lo cual significa que el primer indice corresponde al 0

In [31]:
a

array([1, 2, 3, 4])

In [32]:
a[0] #Veo cual es el valor del array en la posicon del indice[0]

1

In [33]:
a[0]=10 #Modifico el valor del array en la posicion de indice[0]

In [34]:
a

array([10,  2,  3,  4])

In [35]:
a.dtype #Verifico el tipo de dato INT32

dtype('int32')

In [36]:
a[0]=11.4 #Si quiero introducir un tipo de objeto distinto al que originalmente tiene el array el mismo sea truncado (como en este caso de FLOAT a INT)

In [37]:
a

array([11,  2,  3,  4])

In [38]:
a.fill(-4.8) #Intento llenar el array con tipos de datos FLOAT y no puedo ya que el tipo de INT

In [39]:
a

array([-4, -4, -4, -4])

NumPy es MUY ESTRICTO con respecto al tipo de datos que se colocan en un array

In [40]:
a = np.array([1,2,3,4])

In [41]:
a

array([1, 2, 3, 4])

In [42]:
a.dtype #Todos los valores son INT, por lo tanto el tipo de dato del array es INT

dtype('int32')

In [43]:
a = np.array([1,2,3,4.0])

In [44]:
a

array([1., 2., 3., 4.])

In [45]:
a.dtype #Un valor es FLOAT, por lo tanto todos los valores son tomados como float

dtype('float64')

In [46]:
a = np.array([1.0,2.0,3.0,4.0+1j])

In [47]:
a

array([1.+0.j, 2.+0.j, 3.+0.j, 4.+1.j])

In [48]:
a.dtype #Un valor es COMPLEX, por lo tanto todos los valores son tomados como complex

dtype('complex128')

Se tiene disponible utilizar el argumento "dtype" dentro de la declaracion del array para definir el tipo de dato deseado independientemente de los tipos de datos que se utilicen para crear el array

In [53]:
a = np.array([1,2,3,4.0], dtype=int) #Aunque uno de los componentes del array es float defino dentro de los atributos del array que todos los elementos sean int

In [54]:
a

array([1, 2, 3, 4])

In [56]:
a.dtype #Verifico que el tipo de dato sea int32

dtype('int32')